<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.3">
  <POU Name="FB_TimeManagement" Id="{975fdb8f-7a89-4b70-8ffc-4e4ed2f51fc3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FINAL FB_TimeManagement
VAR_IN_OUT
	Control				: ST_System;
	Control_SP			: ST_System_SP;
END_VAR
VAR
	_fb_CurrentTicks	: GETCPUCOUNTER;
	_fb_LocalSystemTime	: FB_LocalSystemTime;
	_CurrentScan		: DWORD := 0;
	_LastScan			: DWORD := 0;
	_LastScanTime		: DWORD := 0;
	_Timer_ET			: DINT;
	_Firstscan			: R_TRIG;
	_MinutePulse		: R_TRIG;
	_HourPulse			: R_TRIG;
	_fb_GetThisTaskIdx	: GETCURTASKINDEX;
	_TaskIndex			: BYTE;
	_TaskCycleCount		: UDINT;
	_TaskCycleCountLast	: UDINT;
	_TaskStarting		: BOOL;
	_StrobeTimer		: TON;
END_VAR
VAR CONSTANT
	_ticksInSecond		: DINT := 10000000;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[A_FirstCycle();
A_LastScanTime();
A_Strobes();
A_SyncSystemTime();
A_TimePulses();
A_UpTime();
]]></ST>
    </Implementation>
    <Action Name="A_FirstCycle" Id="{3a460d9d-cf24-44c7-90fa-34a938acc8b2}">
      <Implementation>
        <ST><![CDATA[_fb_GetThisTaskIdx(INDEX => _TaskIndex);
_TaskCycleCount := _TaskInfo[BYTE_TO_INT(_TaskIndex)].CycleCount;

IF _TaskCycleCount > (_TaskCycleCountLast+100) THEN
	_TaskStarting := 1;
ELSE
	_TaskStarting := 0;	
END_IF
_TaskCycleCountLast := _TaskCycleCount;

_firstscan(CLK:=_TaskStarting);

IF _firstscan.Q THEN
	Control.SystemTime.FirstCycle := TRUE;
ELSE
	Control.SystemTime.FirstCycle := FALSE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_LastScanTime" Id="{a33d16e1-b93a-43c0-8d4b-8073d24ffe0d}">
      <Implementation>
        <ST><![CDATA[_fb_CurrentTicks();
_currentScan := _fb_CurrentTicks.cpuCntLoDW;

IF _lastScan > 0 THEN
	_lastScanTime := _currentScan - _lastScan;
	//Convert to seconds
	Control.SystemTime.ScanTime := DWORD_TO_REAL(_lastScanTime) / DINT_TO_REAL(_ticksInSecond);
END_IF

_lastScan := _currentScan;]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_Strobes" Id="{a9c867b5-2c54-4418-98ee-bbbf290fe418}">
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Ld"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeBox">
                      <o>
                        <v n="BoxType">"TON"</v>
                        <o n="Instance" t="Operand">
                          <v n="Operand">"_strobeTimer"</v>
                          <v n="Type">"TON"</v>
                          <v n="Comment">""</v>
                          <v n="SymbolComment">""</v>
                          <v n="Address">""</v>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <v n="LValue">false</v>
                          <v n="Boolean">false</v>
                          <v n="IsInstance">true</v>
                          <v n="Id">3L</v>
                        </o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <n />
                            <o>
                              <v n="Operand">""</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">5L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <n n="InputFlags" />
                        <l2 n="InputItems" cet="BoxTreeOperand">
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"_strobeTimer.Q"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">" is TRUE, PT seconds after IN had a rising edge "</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">1</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">7L</v>
                            </o>
                            <v n="Id">6L</v>
                          </o>
                          <o>
                            <o n="Operand" t="Operand">
                              <v n="Operand">"T#2000ms"</v>
                              <v n="Type">"TIME"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">false</v>
                              <v n="Boolean">false</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">9L</v>
                            </o>
                            <v n="Id">8L</v>
                          </o>
                        </l2>
                        <o n="InputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>IN</v>
                            <v>PT</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <o n="OutputParam" t="ParamList">
                          <l2 n="Names" cet="String">
                            <v>Q</v>
                            <v>ET</v>
                          </l2>
                          <l2 n="Types" cet="String">
                            <v>BOOL</v>
                            <v>TIME</v>
                          </l2>
                        </o>
                        <v n="CallType" t="Operator">FunctionBlock</v>
                        <v n="EN">false</v>
                        <v n="ENO">false</v>
                        <n n="STSnippet" />
                        <v n="ContainsExtensibleInputs">false</v>
                        <v n="ProvidesSTSnippet">false</v>
                        <v n="Id">4L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">2L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Control.SystemTime.FastFlash"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">34L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeParallel">
                          <l2 n="Trees" cet="BoxTreeBox">
                            <o>
                              <v n="BoxType">"F_LIMIT"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">11L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeTerminator">
                                  <n n="Input" />
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="Id">13L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"500"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">15L</v>
                                  </o>
                                  <v n="Id">14L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"TIME_TO_REAL"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">16L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_strobeTimer.ET"</v>
                                        <v n="Type">"TIME"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">" elapsed time "</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">19L</v>
                                      </o>
                                      <v n="Id">18L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>REAL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Conversion</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">17L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"0"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">21L</v>
                                  </o>
                                  <v n="Id">20L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>En</v>
                                  <v>High</v>
                                  <v>Value</v>
                                  <v>Low</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>REAL</v>
                                  <v>REAL</v>
                                  <v>REAL</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>   </v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Function</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">12L</v>
                            </o>
                            <o>
                              <v n="BoxType">"F_LIMIT"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">22L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeTerminator">
                                  <n n="Input" />
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="Id">24L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"1500"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">26L</v>
                                  </o>
                                  <v n="Id">25L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"TIME_TO_REAL"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">27L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_strobeTimer.ET"</v>
                                        <v n="Type">"TIME"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">" elapsed time "</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">30L</v>
                                      </o>
                                      <v n="Id">29L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>REAL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Conversion</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">28L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"1000"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">32L</v>
                                  </o>
                                  <v n="Id">31L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>En</v>
                                  <v>High</v>
                                  <v>Value</v>
                                  <v>Low</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>REAL</v>
                                  <v>REAL</v>
                                  <v>REAL</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>   </v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Function</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">23L</v>
                            </o>
                          </l2>
                          <n n="Input" />
                          <v n="Mode" t="OperationMode">BoxShortCircuit</v>
                          <v n="Id">33L</v>
                        </o>
                        <v n="Id">35L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">10L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Control.SystemTime.PulseFlash"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">60L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeParallel">
                          <l2 n="Trees" cet="BoxTreeBox">
                            <o>
                              <v n="BoxType">"F_LIMIT"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">76L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeTerminator">
                                  <n n="Input" />
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="Id">39L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"1500"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">41L</v>
                                  </o>
                                  <v n="Id">40L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"TIME_TO_REAL"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">42L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_strobeTimer.ET"</v>
                                        <v n="Type">"TIME"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">" elapsed time "</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">45L</v>
                                      </o>
                                      <v n="Id">44L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>REAL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Conversion</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">43L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"1250"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">47L</v>
                                  </o>
                                  <v n="Id">46L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>En</v>
                                  <v>High</v>
                                  <v>Value</v>
                                  <v>Low</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>LREAL</v>
                                  <v>LREAL</v>
                                  <v>LREAL</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>   </v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Function</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">77L</v>
                            </o>
                            <o>
                              <v n="BoxType">"F_LIMIT"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">48L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems">
                                <o t="BoxTreeTerminator">
                                  <n n="Input" />
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">false</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <v n="Id">50L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"2000"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">52L</v>
                                  </o>
                                  <v n="Id">51L</v>
                                </o>
                                <o t="BoxTreeBox">
                                  <v n="BoxType">"TIME_TO_REAL"</v>
                                  <o n="Instance" t="Operand">
                                    <n n="Operand" />
                                    <v n="Type">""</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">true</v>
                                    <v n="Id">53L</v>
                                  </o>
                                  <o n="OutputItems" t="OutputItemList">
                                    <l2 n="OutputItems">
                                      <n />
                                    </l2>
                                  </o>
                                  <o n="Flags" t="Flags">
                                    <v n="Flags">0</v>
                                    <v n="Fixed">true</v>
                                    <v n="Extensible">false</v>
                                  </o>
                                  <n n="InputFlags" />
                                  <l2 n="InputItems" cet="BoxTreeOperand">
                                    <o>
                                      <o n="Operand" t="Operand">
                                        <v n="Operand">"_strobeTimer.ET"</v>
                                        <v n="Type">"TIME"</v>
                                        <v n="Comment">""</v>
                                        <v n="SymbolComment">" elapsed time "</v>
                                        <v n="Address">""</v>
                                        <o n="Flags" t="Flags">
                                          <v n="Flags">0</v>
                                          <v n="Fixed">false</v>
                                          <v n="Extensible">false</v>
                                        </o>
                                        <v n="LValue">false</v>
                                        <v n="Boolean">false</v>
                                        <v n="IsInstance">false</v>
                                        <v n="Id">56L</v>
                                      </o>
                                      <v n="Id">55L</v>
                                    </o>
                                  </l2>
                                  <o n="InputParam" t="ParamList">
                                    <l2 n="Names" />
                                    <l2 n="Types" />
                                  </o>
                                  <o n="OutputParam" t="ParamList">
                                    <l2 n="Names" cet="String">
                                      <v></v>
                                    </l2>
                                    <l2 n="Types" cet="String">
                                      <v>REAL</v>
                                    </l2>
                                  </o>
                                  <v n="CallType" t="Operator">Conversion</v>
                                  <v n="EN">false</v>
                                  <v n="ENO">false</v>
                                  <n n="STSnippet" />
                                  <v n="ContainsExtensibleInputs">false</v>
                                  <v n="ProvidesSTSnippet">false</v>
                                  <v n="Id">54L</v>
                                </o>
                                <o t="BoxTreeOperand">
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"1750"</v>
                                    <v n="Type">"INT"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">""</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">58L</v>
                                  </o>
                                  <v n="Id">57L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>En</v>
                                  <v>High</v>
                                  <v>Value</v>
                                  <v>Low</v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                  <v>REAL</v>
                                  <v>REAL</v>
                                  <v>REAL</v>
                                </l2>
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v>   </v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>BOOL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Function</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">49L</v>
                            </o>
                          </l2>
                          <n n="Input" />
                          <v n="Mode" t="OperationMode">BoxShortCircuit</v>
                          <v n="Id">59L</v>
                        </o>
                        <v n="Id">61L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">36L</v>
                  </o>
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" cet="BoxTreeAssign">
                      <o>
                        <o n="OutputItems" t="OutputItemList">
                          <l2 n="OutputItems" cet="Operand">
                            <o>
                              <v n="Operand">"Control.SystemTime.SlowFlash"</v>
                              <v n="Type">"BOOL"</v>
                              <v n="Comment">""</v>
                              <v n="SymbolComment">""</v>
                              <v n="Address">""</v>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="LValue">true</v>
                              <v n="Boolean">true</v>
                              <v n="IsInstance">false</v>
                              <v n="Id">74L</v>
                            </o>
                          </l2>
                        </o>
                        <o n="Flags" t="Flags">
                          <v n="Flags">0</v>
                          <v n="Fixed">false</v>
                          <v n="Extensible">false</v>
                        </o>
                        <o n="RValue" t="BoxTreeBox">
                          <v n="BoxType">"F_LIMIT"</v>
                          <o n="Instance" t="Operand">
                            <n n="Operand" />
                            <v n="Type">""</v>
                            <v n="Comment">""</v>
                            <v n="SymbolComment">""</v>
                            <v n="Address">""</v>
                            <o n="Flags" t="Flags">
                              <v n="Flags">0</v>
                              <v n="Fixed">false</v>
                              <v n="Extensible">false</v>
                            </o>
                            <v n="LValue">false</v>
                            <v n="Boolean">false</v>
                            <v n="IsInstance">true</v>
                            <v n="Id">63L</v>
                          </o>
                          <o n="OutputItems" t="OutputItemList">
                            <l2 n="OutputItems">
                              <n />
                            </l2>
                          </o>
                          <o n="Flags" t="Flags">
                            <v n="Flags">0</v>
                            <v n="Fixed">false</v>
                            <v n="Extensible">false</v>
                          </o>
                          <n n="InputFlags" />
                          <l2 n="InputItems">
                            <o t="BoxTreeTerminator">
                              <n n="Input" />
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">false</v>
                                <v n="Extensible">false</v>
                              </o>
                              <v n="Id">65L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"1000"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">67L</v>
                              </o>
                              <v n="Id">66L</v>
                            </o>
                            <o t="BoxTreeBox">
                              <v n="BoxType">"TIME_TO_REAL"</v>
                              <o n="Instance" t="Operand">
                                <n n="Operand" />
                                <v n="Type">""</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">true</v>
                                <v n="Id">68L</v>
                              </o>
                              <o n="OutputItems" t="OutputItemList">
                                <l2 n="OutputItems">
                                  <n />
                                </l2>
                              </o>
                              <o n="Flags" t="Flags">
                                <v n="Flags">0</v>
                                <v n="Fixed">true</v>
                                <v n="Extensible">false</v>
                              </o>
                              <n n="InputFlags" />
                              <l2 n="InputItems" cet="BoxTreeOperand">
                                <o>
                                  <o n="Operand" t="Operand">
                                    <v n="Operand">"_strobeTimer.ET"</v>
                                    <v n="Type">"TIME"</v>
                                    <v n="Comment">""</v>
                                    <v n="SymbolComment">" elapsed time "</v>
                                    <v n="Address">""</v>
                                    <o n="Flags" t="Flags">
                                      <v n="Flags">0</v>
                                      <v n="Fixed">false</v>
                                      <v n="Extensible">false</v>
                                    </o>
                                    <v n="LValue">false</v>
                                    <v n="Boolean">false</v>
                                    <v n="IsInstance">false</v>
                                    <v n="Id">71L</v>
                                  </o>
                                  <v n="Id">70L</v>
                                </o>
                              </l2>
                              <o n="InputParam" t="ParamList">
                                <l2 n="Names" />
                                <l2 n="Types" />
                              </o>
                              <o n="OutputParam" t="ParamList">
                                <l2 n="Names" cet="String">
                                  <v></v>
                                </l2>
                                <l2 n="Types" cet="String">
                                  <v>REAL</v>
                                </l2>
                              </o>
                              <v n="CallType" t="Operator">Conversion</v>
                              <v n="EN">false</v>
                              <v n="ENO">false</v>
                              <n n="STSnippet" />
                              <v n="ContainsExtensibleInputs">false</v>
                              <v n="ProvidesSTSnippet">false</v>
                              <v n="Id">69L</v>
                            </o>
                            <o t="BoxTreeOperand">
                              <o n="Operand" t="Operand">
                                <v n="Operand">"0"</v>
                                <v n="Type">"INT"</v>
                                <v n="Comment">""</v>
                                <v n="SymbolComment">""</v>
                                <v n="Address">""</v>
                                <o n="Flags" t="Flags">
                                  <v n="Flags">0</v>
                                  <v n="Fixed">false</v>
                                  <v n="Extensible">false</v>
                                </o>
                                <v n="LValue">false</v>
                                <v n="Boolean">false</v>
                                <v n="IsInstance">false</v>
                                <v n="Id">73L</v>
                              </o>
                              <v n="Id">72L</v>
                            </o>
                          </l2>
                          <o n="InputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>En</v>
                              <v>High</v>
                              <v>Value</v>
                              <v>Low</v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                              <v>REAL</v>
                              <v>REAL</v>
                              <v>REAL</v>
                            </l2>
                          </o>
                          <o n="OutputParam" t="ParamList">
                            <l2 n="Names" cet="String">
                              <v>   </v>
                            </l2>
                            <l2 n="Types" cet="String">
                              <v>BOOL</v>
                            </l2>
                          </o>
                          <v n="CallType" t="Operator">Function</v>
                          <v n="EN">false</v>
                          <v n="ENO">false</v>
                          <n n="STSnippet" />
                          <v n="ContainsExtensibleInputs">false</v>
                          <v n="ProvidesSTSnippet">false</v>
                          <v n="Id">64L</v>
                        </o>
                        <v n="Id">75L</v>
                      </o>
                    </l2>
                    <l2 n="Connectors" />
                    <v n="Id">62L</v>
                  </o>
                </l2>
                <v n="BranchCounter">0</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="BoxTreeAssign">{9873c309-1f09-4ebf-9078-42d8057ef11b}</Type>
              <Type n="BoxTreeBox">{acfc6f68-8e3a-4af5-bf81-3dd512095a46}</Type>
              <Type n="BoxTreeOperand">{9de7f100-1b87-424c-a62e-45b0cfc85ed2}</Type>
              <Type n="BoxTreeParallel">{827b9ec2-2032-40da-9f4e-7670ca2d55a8}</Type>
              <Type n="BoxTreeTerminator">{5f9848d3-568d-4cc5-9e31-8e28e9607ff1}</Type>
              <Type n="Flags">{668066f2-6069-46b3-8962-8db8d13d7db2}</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="Operand">{c9b2f165-48a2-4a45-8326-3952d8a3d708}</Type>
              <Type n="OperationMode">{3b9474d0-c98b-4935-8ce5-65f06808350d}</Type>
              <Type n="Operator">{bffb3c53-f105-4e85-aba2-e30df579d75f}</Type>
              <Type n="OutputItemList">{f40d3e09-c02c-4522-a88c-dac23558cfc4}</Type>
              <Type n="ParamList">{71496971-9e0c-4677-a832-b9583b571130}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Action>
    <Action Name="A_SyncSystemTime" Id="{e7263b84-2d59-4eb2-af20-779c52a5518b}">
      <Implementation>
        <ST><![CDATA[_fb_LocalSystemTime(sNetID := '', bEnable := TRUE, dwCycle := 15, dwOpt := 1, tTimeout := DEFAULT_ADS_TIMEOUT);
IF _fb_LocalSystemTime.bValid THEN
	Control.SystemTime.CurrentTime := _fb_LocalSystemTime.systemTime;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_TimePulses" Id="{d3adb398-20dc-4798-8f4a-889bb17c9470}">
      <Implementation>
        <ST><![CDATA[//Second Pulse
_timer_ET := _timer_ET + DWORD_TO_DINT(_lastScanTime);
IF _timer_ET >= _ticksInSecond THEN 
	Control.SystemTime.SecondPulse := TRUE;
	Control.SystemTime.SecondsNow := TO_DWORD(SYSTEMTIME_TO_DT(Control.SystemTime.CurrentTime));
	_timer_ET := 0;
ELSE
	Control.SystemTime.SecondPulse := FALSE;
END_IF

//Minute Pulse
_MinutePulse(CLK := Control.SystemTime.CurrentTime.wSecond = 0);
Control.SystemTime.MinutePulse :=  _MinutePulse.Q;

//Hour Pulse
_HourPulse(CLK := Control.SystemTime.CurrentTime.wMinute = 0);
Control.SystemTime.HourPulse :=  _HourPulse.Q;

//Midnight Pulse
IF WORD_TO_INT(Control.SystemTime.CurrentTime.wDay) <> Control_SP.TimeManagement.PreviousDay THEN
	Control.SystemTime.MidnightPulse := TRUE;
	Control_SP.TimeManagement.PreviousDay := WORD_TO_INT(Control.SystemTime.CurrentTime.wDay);
ELSE
	Control.SystemTime.MidnightPulse := FALSE;
END_IF]]></ST>
      </Implementation>
    </Action>
    <Action Name="A_UpTime" Id="{3c8d1c80-a152-4c57-8088-34dc86e1e8e3}">
      <Implementation>
        <ST><![CDATA[IF Control.SystemTime.SecondPulse THEN
	//Up time since last reset
	Control.SystemTime.UpTime.Seconds := Control.SystemTime.UpTime.Seconds + 1;
	IF Control.SystemTime.UpTime.Seconds >= 60 THEN 
		Control.SystemTime.UpTime.Minutes := Control.SystemTime.UpTime.Minutes + 1;
		Control.SystemTime.UpTime.Seconds := 0;
	END_IF
	IF Control.SystemTime.UpTime.Minutes >= 60 THEN 
		Control.SystemTime.UpTime.Hours := Control.SystemTime.UpTime.Hours + 1;
		Control.SystemTime.UpTime.Minutes := 0;
	END_IF
	IF Control.SystemTime.UpTime.Hours >= 24 THEN 
		Control.SystemTime.UpTime.Days := Control.SystemTime.UpTime.Days + 1;
		Control.SystemTime.UpTime.Hours := 0;
	END_IF
	
	//Total up time
	Control_SP.TimeManagement.TotalUpTime.Seconds := Control_SP.TimeManagement.TotalUpTime.Seconds + 1;
	IF Control_SP.TimeManagement.TotalUpTime.Seconds >= 60 THEN 
		Control_SP.TimeManagement.TotalUpTime.Minutes := Control_SP.TimeManagement.TotalUpTime.Minutes + 1;
		Control_SP.TimeManagement.TotalUpTime.Seconds := 0;
	END_IF
	IF Control_SP.TimeManagement.TotalUpTime.Minutes >= 60 THEN 
		Control_SP.TimeManagement.TotalUpTime.Hours := Control_SP.TimeManagement.TotalUpTime.Hours + 1;
		Control_SP.TimeManagement.TotalUpTime.Minutes := 0;
	END_IF
	IF Control_SP.TimeManagement.TotalUpTime.Hours >= 24 THEN 
		Control_SP.TimeManagement.TotalUpTime.Days := Control_SP.TimeManagement.TotalUpTime.Days + 1;
		Control_SP.TimeManagement.TotalUpTime.Hours := 0;
	END_IF
END_IF]]></ST>
      </Implementation>
    </Action>
    <LineIds Name="FB_TimeManagement">
      <LineId Id="3" Count="1" />
      <LineId Id="35" Count="0" />
      <LineId Id="5" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_TimeManagement.A_FirstCycle">
      <LineId Id="17" Count="0" />
      <LineId Id="13" Count="1" />
      <LineId Id="18" Count="0" />
      <LineId Id="20" Count="1" />
      <LineId Id="19" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="15" Count="1" />
      <LineId Id="12" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="4" Count="2" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_TimeManagement.A_LastScanTime">
      <LineId Id="2" Count="8" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_TimeManagement.A_SyncSystemTime">
      <LineId Id="2" Count="2" />
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_TimeManagement.A_TimePulses">
      <LineId Id="20" Count="0" />
      <LineId Id="24" Count="2" />
      <LineId Id="40" Count="0" />
      <LineId Id="27" Count="2" />
      <LineId Id="21" Count="0" />
      <LineId Id="35" Count="0" />
      <LineId Id="8" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="17" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="37" Count="1" />
      <LineId Id="36" Count="0" />
      <LineId Id="47" Count="0" />
      <LineId Id="32" Count="2" />
      <LineId Id="14" Count="0" />
    </LineIds>
    <LineIds Name="FB_TimeManagement.A_UpTime">
      <LineId Id="2" Count="29" />
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>